### ISSUE TITLE
Endless loop in table_drop_pre_trigger function

### ISSUE THREAD

**Issue by nextstopsun** [pgMemento/pgMemento#32] opened 2019-06-03 09:46 UTC
I've got an endless loop from a simple command:
```DROP TABLE IF EXISTS myschema.nonexisting_table CASCADE;```

Digging into a code of `table_drop_pre_trigger` function, I've found that [this line](https://github.com/pgMemento/pgMemento/blob/master/src/DDL_LOG.sql#L938) causes trouble. 
It sets `fetch_next` variable to `TRUE` and this results in endless loop.

@FxKu Can you please explain the logic behind this `EXCEPTION` block? Why does it set `fetch_next` to `FALSE` on `invalid_name` and to `TRUE` on `undefined_table`? Isn't `NULL` and invalid name?

**Comment by FxKu** [comment] 2019-06-03 12:20
Was probably my thinking. Can't remember exactly when `invalid_name occurred`. I've added exit conditions to this while loop in case the string is NULL.

**Comment by FxKu** [comment] 2019-06-03 12:23
I'm also wondering why this error happened, because your DDL command looks fine. Or is this table not being audited?

**Comment by nextstopsun** [comment] 2019-06-03 14:39
This is the first table I create after 
```
SELECT pgmemento.create_schema_event_trigger(TRUE);
```

**Comment by nextstopsun** [comment] 2019-06-03 15:41
@FxKu check on zero length fails because `length(table_ident) = 0` returns `FALSE` as length of `NULL` is not zero.

Try this
```
SELECT pgmemento.create_schema_event_trigger(TRUE);
CREATE SCHEMA IF NOT EXISTS myschema;
DROP TABLE IF EXISTS myschema.mytable CASCADE;
```

You still get an endless loop.

**Comment by FxKu** [comment] 2019-06-03 22:12
Hm, I couldn't reproduce this error. Table got dropped and logs were as expected. I've added an additional NULL check to be sure. Wonder what's causing this on your side? It seems that the DDL context could not be parsed correctly. Or maybe the `flatten_ddl` function removes too much?

**Comment by nextstopsun** [comment] 2019-06-04 13:22
Ok, let me try to debug this. 
What PG version are you testing this on?

**Comment by dnsl48** [comment] 2019-06-04 21:14
> What PG version are you testing this on?

We run tests [covering 9.5 to 11](https://github.com/pgMemento/pgMemento/blob/master/.travis.yml)

**Comment by FxKu** [comment] 2019-06-17 16:04
@nextstopsun some new findings here?

**Comment by nextstopsun** [comment] 2019-06-18 15:06
@FxKu Your last added check on non NULL fixed that for my case. 
Still wonder why you didn't get an endless loop in your tests.

**Comment by FxKu** [comment] 2019-06-19 21:58
But can you also make sure that everything is logged as expected? As I said before, I believe the error only ocurred because the parsing result has been empty. You could just throw your query at the `flatten_ddl` function and see what it returns.

**Comment by FxKu** [comment] 2020-04-10 09:49
Closing as endless loops are fixed. Feel free to reopen if you spot them with the latest version from master.

**Closed by FxKu** 2020-04-10 09:49 UTC
Labels: bug
